name: Build & Push Prod
on:
  push:
    tags:
      - "*"
jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build ui image
      run: |
        docker build -t zme-ui .
    - name: Tag images
      run: |
        docker tag zme-ui ghcr.io/memphis-artcc/ui:latest
        docker tag zme-ui ghcr.io/memphis-artcc/ui:${{ env.RELEASE_VERSION }}
    - name: Push images
      run: |
        docker push ghcr.io/memphis-artcc/ui:latest
        docker push ghcr.io/memphis-artcc/ui:${{ env.RELEASE_VERSION }}